---

xcat_mellanox_directory: "{{ xcat_ansible_dir }}/ansible/mellanox" 

xcat_mellanox_installer_src: "/opt/xcat/share/xcat/ib/scripts/Mellanox/mlnxofed_ib_install.v2"
xcat_mellanox_installer_script_name: "{{ copycds_name }}-custom-mlnxofed_ib_install"

xcat_postscripts_dir: "{{ xcat_install_dir }}/postscripts" 
xcat_custom_mlnx_installer: "{{ xcat_postscripts_dir }}/{{ xcat_mellanox_installer_script_name }}"

mellanox_iso_file: "{{ xcat_custom_diskful_dir }}/{{ mellanox_iso_file_name }}"
