---
# Default variables for cuda 
#

xcat_cuda_dir: "{{ xcat_ansible_dir }}/cuda"

xcat_cuda_tmpdir: /tmp/xcat_cuda_tmp

cuda_version_str: "cuda-{{ cuda_version }}"
xcat_cuda_version: "{{ xcat_cuda_dir }}/{{ cuda_version_str }}"
xcat_cuda_fullpath: "{{ xcat_cuda_version }}/{{ cuda_iso_arch }}"
xcat_cuda_fullpath_cudacore: "{{ xcat_cuda_fullpath }}/cuda-core"
xcat_cuda_fullpath_cudadeps: "{{ xcat_cuda_fullpath }}/cuda-deps"

xcat_cuda_rhels7_sample_pkglist: "/opt/xcat/share/xcat/install/rh/cudafull.rhels7.ppc64le.pkglist"
