#!/bin/bash

if [[ -z ${1} ]]; then 
    echo "ERROR: Provide the name of the osimage to modify!" 
    exit 1
fi 

if [[ -z ${2} ]]; then 
    echo "ERROR: Provide the IP address of the management node"
    exit 1
fi 


OSIMAGE=${1}
MGMT_IP=${2}
NETBOOT=`lsdef -t osimage ${OSIMAGE} -i provmethod -c | cut -d' ' -f2 | cut -d= -f2` 

if [[ ${NETBOOT} != "netboot" ]]; then 
    echo "This is not a diskless image, nothing to do..."
    exit 0
fi 

ROOTIMGDIR=`lsdef -t osimage ${OSIMAGE} -i rootimgdir -c | cut -d' ' -f2 | cut -d= -f2`

YUM_REPOS="${ROOTIMGDIR}/rootimg/etc/yum.repos.d/"
YUM_REPOS_FILE="${YUM_REPOS}/local.repo"
if [[ ! -d $YUM_REPOS ]]; then
    echo "ERROR: There's no repo directory here: ${YUM_REPOS}, was genimage ran?"
    exit 1
fi 

echo "Creating repo file here: ${YUM_REPOS_FILE}"

PKG_DIR=`lsdef -t osimage ${OSIMAGE} -i pkgdir -c | cut -d' ' -f2 | cut -d= -f2`
OS_DISTRO_NAME=`lsdef -t osimage ${OSIMAGE} -i osdistroname -c | cut -d' ' -f2 | cut -d= -f2`


echo "[local-$OS_DISTRO_NAME-repo]" > ${YUM_REPOS_FILE}
echo "name=Local repo generated by a script for the diskless image" >> ${YUM_REPOS_FILE}
echo "baseurl=http://${MGMT_IP}/$PKG_DIR" >> ${YUM_REPOS_FILE}
echo "enabled=1" >> ${YUM_REPOS_FILE}
echo "gpgcheck=0" >> ${YUM_REPOS_FILE}

cat ${YUM_REPOS_FILE}
exit 0
